# Generated by Django 4.0.4 on 2022-07-10 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ('-create_at',)},
        ),
    ]
