# Generated by Django 4.0.4 on 2022-07-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0002_alter_blogmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('slug', models.SlugField(max_length=10000)),
                ('image', models.ImageField(upload_to='blog')),
                ('content', models.CharField(max_length=100000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('upload_to', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
        migrations.DeleteModel(
            name='BlogModel',
        ),
    ]
