# Generated by Django 4.0.4 on 2022-07-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
